environment:
  BOOST_ROOT: c:\Libraries\boost
  BOOST_LIBRARYDIR: c:\Libraries\boost\stage\lib
  matrix:
    - GENERATOR: "Visual Studio 12"
      CONFIG: Debug

init:
  - cmd: cmake --version

build_script:
  - cmake -G"%GENERATOR%" -H. -Bbuild -DBOOST_ROOT="%BOOST_ROOT%" -DBOOST_LIBRARYDIR="%BOOST_LIBRARYDIR%" -DBoost_USE_STATIC_LIBS="ON"
  - cmake --build build --config "%CONFIG%"

test_script:
  - ps: cd build
  - ps: cd test
  - ctest -C "%CONFIG%" -VV